FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y software-properties-common apt-utils locales tzdata
RUN echo "tzdata tzdata/Areas select Asia" > timezone.txt
RUN echo "tzdata tzdata/Zones/Asia select Kuala_Lumpur" >> timezone.txt
RUN debconf-set-selections timezone.txt
RUN rm /etc/timezone
RUN rm /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

COPY ./apache-tomcat-7.0.75.tar.gz /tmp/apache-tomcat-7.0.75.tar.gz
COPY ./jdk-7u80-linux-x64.tar.gz /tmp/jdk-7u80-linux-x64.tar.gz
RUN tar zxvf /tmp/apache-tomcat-7.0.75.tar.gz -C /usr/local
RUN tar zxvf /tmp/jdk-7u80-linux-x64.tar.gz -C /usr/local
RUN ln -s /usr/local/apache-tomcat-7.0.75 /usr/local/tomcat
RUN ln -s /usr/local/jdk1.7.0_80 /usr/local/jdk
ENV CATALINA_HOME=/usr/local/tomcat
ENV JAVA_HOME=/usr/local/jdk

