FROM horngyih/java:jdk7

WORKDIR /tmp
RUN wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.75/bin/apache-tomcat-7.0.75.tar.gz  
RUN tar zxvf apache-tomcat*.gz -C /usr/local/

WORKDIR /usr/local/
RUN ln -s apache-tomcat-7.0.75 tomcat
RUN chmod -R 755 tomcat
ENV CATALINA_HOME=/usr/local/tomcat

WORKDIR /usr/local/tomcat
CMD $CATALINA_HOME/bin/catalina.sh jpda run

